image: buildpack-deps:focal

stages:
  - build
  - test

variables:
  BTC_LIB_DIR: "/usr/local"

before_script:
  - apt-get update
  - apt-get install -y cmake libtool autoconf pkg-config git libgtest-dev
  - git clone https://github.com/libbtc/libbtc.git /tmp/libbtc
  - cd /tmp/libbtc
  - ./autogen.sh
  - ./configure --prefix=$BTC_LIB_DIR
  - make -j$(nproc)
  - make install
  - cd $CI_PROJECT_DIR
  - echo "libbtc installed!"

build-job:
  stage: build
  tags:
    - shared-fi
  script:
    - make build

unit-test-job:
  stage: test
  tags:
    - shared-fi
  script:
    - cd /usr/src/gtest
    - cmake .
    - make
    - cp lib/*.a /usr/lib
    - cd $CI_PROJECT_DIR
    - make test-build
    - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
    - make test

integration-test-job:
  stage: test
  tags:
    - shared-fi
  script:
    - cd src/tests
    - chmod +x integration_tests.sh
    - ./integration_tests.sh
