# .gitlab-ci.yml
image: ubuntu:20.04

stages:
  - build
  - test

build-job:
  stage: build
  tags:
    - shared-fi       # <--- This is where we use the 'shared-fi' tag.
  script:
    - apt-get update && apt-get install -y build-essential
    - make build

test-job:
  stage: test
  tags:
    - shared-fi       # <--- Also use the same tag for your test job
  script:
    - apt-get update && apt-get install -y build-essential libgtest-dev cmake
    - cd /usr/src/gtest && cmake . && make && mv lib/libgtest*.a /usr/lib && cd -
    - make test-build
    - make test
